name: updateList

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: update content
        run: ls cover post

      - name: push to content
        run: |
          git add content.txt
          git commit -m "updated content.txt"
          git push origin HEAD:main
