name: updateList

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: test
        run: ls

      - name: update content
        run: ls cover post > content.txt && cat content.txt

      - name: push to content
        run: |
          git config --local user.name "tristanlukens"
          git add content.txt
          git commit -m "updated content.txt"
          git remote set-url origin ${{ secrets.ssh }}
          git fetch origin main
          git push origin HEAD:main
